### ISSUE TITLE
TFXC Accept All Traffic Routing Logic Adjustment

### ISSUE THREAD

**Issue by teliaxdavec** [tfxc/issues#42] opened 2020-08-08 03:38 UTC
Story:

As a partner on the TFX Exchange, I would like the exchange to terminate, via the PSTN, all traffic that does not peer [when "accept all traffic is enabled on the ROID edit screen"

Current Behavior:

When "accept all traffic" option is checked in the ROID edit screen, any traffic that is bound for a ROID that is not a partner on the Exchange is terminated to the PSTN via our ULC, Teliax (using system AAA99).  
Any traffic that is bound for a Partner/Active ROID on the exchange, but is a financial mis-match (non-peering) is pushed back to the originating partner as a 503 Route Advance (or 302 redirect w/CIC if option is chosen).

Requested Behavior:

When "Accept all traffic" is checked on the ROID edit screen, ALL non-peered traffic (regardless of partner status) is terminated to the PSTN via our ULC, Teliax (using system AAA99).

Notes from Engineering: David Capece discussed this with David in https://it.teliax.com/helpdesk/tickets/660#tasks and David is aligned with Christy Belcher/TFXC's feature request.

**Comment by CascadiaSnow** [comment] 2020-09-22 19:12
Updated Information for current behavior:  additional discussions have led us to understand that when "accept all traffic" is checked and the financial mismatch is due to the ceiling rate being lower then the sell rate , the call is pushed down AAA99.  If the terminating partner has a rate deck uploaded and there is a financial mismatch, the traffic is 503 route advanced.

**Comment by CarlsBad505** [comment] 2020-10-12 20:13
Additional notes from Christy:

"We only have 3 partners who currently use "Accept All Traffic".  Kall 8 (IWL11), Route Trust (RZA22), and Dial Pad (ZYF99).  Since the feature is not currently designed to Accept traffic that is a Rate Deck mismatch (will 503 Roue Advance regardless of "Accept All Traffic" option)  it will need to be coded into the current design."

**Comment by CarlsBad505** [comment] 2020-10-12 21:14
Notes to Self:

Views is simply persisting whether or not a ROID is going to "Accept All Traffic". This persistence is mapped to an attribute in the resporg_account_ids table called `origin_traffic_default_routed` - type boolean. When this value is either updated or created for a ROID, Views will handle data persistence, configurations for a ROID. That's it. It does not handle rules about call traffic.

So naturally, it smells like this is logic resides elsewhere. If we look at Policy Router application, specifically here: (https://github.com/tfxc/policy_router/blob/master/models/resporg_account_id.rb#L120) we see that the class `ResporgAccountId` in Policy Router is 1) sharing the same database as Views (see the sample database.yml file) and 2) has a custom instance method `has_default?` to call if "Accept all Traffic" is true or false. Now the meat of this resides here (https://github.com/tfxc/policy_router/blob/b9bed4a7285dbbfa3263d34de42f1e2e0aeacfac/lib/policy_router/events/route_event.rb#L109) where if you read the file, this smells a lot more like where the routing logic in question resides.

**TODO:**
Because I've never looked at Policy Router before and its also extremely complex, I suggest we dig deeper, come up with a theory of where the code should be changed, and then solicit the India team to ensure they agree. Changing code in Policy Router is high risk and can break traffic routing logic. As someone who did not originate this code, lets mitigate this risk by asking those who did originate the code...

**Comment by CarlsBad505** [comment] 2020-10-13 22:50
If we look at this line here (https://github.com/tfxc/policy_router/blob/master/lib/policy_router/events/route_event.rb#L161), this is where we attempt to look up the rate by the `npanxx` otherwise known to be something on the rate protection decks. You'll see that if we don't find it, we default to the terminating resporgs own `terminating_sip_trunk_ceiling_rate`. Either way, when we don't find a direct peered deal, we fall back to either the NPANXX rate **OR** the terminating resporgs own `terminating_sip_trunk_ceiling_rate` on line #168. Then we use this rate (the `term_resporg_ceiling_rate`) to compare to see if the `orig_resporg_sell_rate` is <= to the `term_resporg_ceiling_rate` on line #130 of the compare! method. If this condition is not satisfied, only then do we fall next to the "Accept All Traffic" conditional and if this is true, then we set the terminating resporg to system (AAA99). At this time, we return true and we also do not do a rate protection comparison anymore either. Returning true means the method `lookup!` also returns true and we proceed to move on to Freeswitch recursively...

The only time we send a 503 is when when the method `send_error!` is invoked. This only happens as the last `else` statement of the conditional blocks in `look_up!` and `compare!` and also when a specific Individual Sell Rate is explicitly blocked.

**Comment by CarlsBad505** [comment] 2020-10-22 22:29
More notes... Joe Green found this... could it be related?

"Christy and Patrice found an issue on the TFX network.  Resporgs in the TFX can add 10 digit call blocking to their account, basically if the toll free exchange gets a call to this number, all though I own it, I don't want the call until I can complete routing to the number on my end.  Until then reject every call to that number I own with a 503. Once routing is done I can readd it.  We found five9 for example has a ton of numbers they reject, most of them they are the resporg, however some of them they are not the resporg.  I am not sure why five9 would reject a number to them in which they are not the resporg, mistake on their part?  they didn't mean to add it to 10 digit call routing rejection?  On these numbers where they aren't the resporg, the actual resporg is on the TFX network and we should route it to them and make money but we do not.  The call is rejected globally for all customers.  Our network should say, I have a call to a number, I have a term resporg, now check if the number is on that term resporgs 10 digit calling list to reject, if not send the call to them.  Not I have a call to a number, oh it's on a 10 digit calling list, block globally despite the fact that this is on the wrong resporgs calling list."

**Comment by CascadiaSnow** [comment] 2020-10-22 23:39
Carl, I have wondered the same thing.  I was actually searching for your
requested call examples when I stumbled down this rabbit hole. It does
explain a 503 when accept all traffic is checked... Especially given that
we couldn't find anything in the code.

Christy Belcher
Director of Partner Operations
O: 833-235-2437
123456789101112

**Comment by daldworth** [comment] 2020-10-22 23:44
No, these are not related. At least not logically. I cannot speak to the
code. However, they are common in that each is an order-of-operations
issue.

*Issue #1 "Accept All Routing"...*
*Background:*
*Note that i refer to "Accept all Routing" and "Default Routing" as one and
the same.*

The TFX is designed to connect an originating Resp Org (i.e. an entity who
is sending a TF call to the TFX) with a terminating Resp Org (i.e. an
organization receiving a TF call from the TFX). When a call from an
originating resp org is received by a terminating resp org on the TFX we
refer to that all as being 'peered'. Since the TFX does not represent all
Resp Orgs in existence - only those who have registered with the TFX can
orig/term a call - some calls that are sent to the TFX are destined for
Resp Orgs not represented. When a Resp Org sends a call to the TFX in such
a case, they have the option of having the TFX reject the call or "default
route" the call. Let's first look at the reject scenario. Reject scenario
B: If the sender asks for the call to be rejected, they have the options of
receiving a flat reject in the form of a SIP 503 response. We simple say
"Service Unavailable". Reject scenario B: Or, they can receive a SIP 302
Redirect which contains the Carrier Identification code "CIC" applicable to
the call. The CIC code value comes from an API call to the same CIC DIP
service that Teliax uses for 8YY routing. The CIC is stuffed into the 302
response to the upstream sending carrier. Default routed scenario: The
customer may not want the call to get sent back to them but instead ask the
TFX to complete all calls which can be completed. We call this "default
routing". If the customers called cannot be peeed to another resp org on
the TFX, and they have default routing turned on, then the TFX will route
the call to the PSTN. In this case, by "PSTN" we mean the TFX will send the
call to Teliax where Teliax will perform it's 8yy routing service for the
TFX just as it would any other 8yy customer. In theory, if the call can
complete, it will complete and the upstream TFX customers call is answered.

The unique scenario we are looking at here is a call that was sent to the
TFX by an upstream originating Resp Org that is destined to a TFNumber that
*is* associated to a resp org on the TFX but that call cannot complete. In
this scenario, the originating Resp Org does have default routing enabled.
However, for one of many possible reasons which we will explain, the call
does not complete to that terminating (recipient) resp org. The question in
this scenario is: should the call then be default routed or not? The answer
is it depends on *why* the call was rejected. I will categorize the types
of rejects as "internal" and "external". Meaning, was it logic internal to
the TFX that caused the call to not attempt to connect to the terminating
Resp Org (onnet reject), or did the TFX make an attempt to connect the call
to the terminating Resp Org and the terminating Resp Org rejected the call
(offnet reject). There are three reasons why the TFX my internally reject
the call: 1) Rate mismatch. Rates must match for calls to be peered. A
match means that the originating/sending Resp Org has offered a "sell rate"
(a rate for which it expects to be paid) that is <= to the "ceiling rate"
(the highest rate the receiving resp org is willing to pay) that is set by
the terminating/receiving resp org. This ceiling rate may come in the form
of a "default" rate, an "individual" rate or a "price protection" rate that
comes from a rate deck loaded into the TFX by the terminating/receiving
resp org. No matter the match methodology, if the prices do not match, the
call will be rejected internally. 2) 10 digit reject. Receiving resp orgs
have the option of setting filters for numbers which match at the 10 digit
level which they do not want to receive calls for. There are myriad
legitimate reasons why they may want to do this which we will not get into
here. 3) The RespOrg ID is "deleted" which is a euphemism for inactive (we
don't actually delete the resp org id).

*Expected Behavior for Default Routed Calls *onnet**
In scenario #1: Rate Mismatch, calls should be default routed to the PSTN.
In scenario #2: 10 digit reject, calls should be default routed to the PSTN.
In scenario #3: Inactive recipent, calls hould be default routed to the PSTN

*Expected Behavior for Default Routed Calls *offnet**
Calls expected to terminate to a Resp Org on the TFX where that receiving
Resp Org then rejects the calls should be rejected all the way back to the
originating carrier. This is justified for many reasons, such as the fact
that if we reject the call back to the originating carrier they will likely
advance that call to a secondary route which may or may not get the same
result as that of the TFX sending calls to the receiving carrier. Or, if
the call was default routed the call would likely get the same result via
the TFX for the second "bite at the apple". All of which can introduce
unnecessary Post Dial Delay on a call which the receiving carrier has
effective chosen to not handle. If the calls is not handled by the
receiving carrier because of interop issues then those interop issues
should be poste haste addressed, not side steped. There are endless
possibilities, but if we have a downstream peered carrier who has responded
to a call attempt, it stands to reason that response should be relayed, not
obfuscated.

*Defect hypothesis*
Disclaimer, i'm not 100% familiar with this issue. My understanding is that
we are not default routing "onnet" calls but instead relaying the 503 to
the upstream carrier when the call was not peered for internal reasons. If
that is true, this behavior should be changed. Onnet rejects should be
default routed if the upstream resp org has requested calls be default
routed. I'm am not sure if this is true of onnet reject scenario #1, #2 and
#3 or a subset thereof. Offnet rejects, however, should not be default
routed.

*Issue #2: Global 10 digit blocking...*
*Background:*
Receiving Resp Orgs have the option of handing calls at the 10 digit level.
This allows them to use the TFX to route calls to separate downstream IP
addresses based on the destination dialed TFN. For example, I own
1800FLOWERS (Resp Org ABC99) and I also own 1800AIRPLANE (also Resp Org
ABC99) but i want calls to 1800FLOWERS to go to IP address 1.2.3.4 and I
want calls to 1800AIRPLANE to go to IP address 4.5.6.7. The TFX provides
this functionality. Additionally, the TFX allows receiving resp orgs to
block, or reject, calls to a ten digit number. While there are a few
scenarios where this makes sense, the most prominent is when a number is
porting from carrier to carrier. The new carrier, who is on the TFX, is not
prepared to actually route the calls yet (a step commonly referred to as
"translations"). So, while the number may be with the new Resp Org who is
on the TFX, the legacy CIC code based routing has not been changed. Since
the TFX is a mutually exclusive way of routing to CIC routing, we have to
bridge that time between the old and the new when a number is ported. While
that translation is happening a Resp Org may want to block the 10 digit
number.

*Defect:*
When implementing this features we consciously did not filter 10 digit
TFN's entered by the terminating resp org based on their Resp Org ID.
Meaning, If Ring Central (RBI99) entered 1800FLOWERS into their 10 digit
block list, even though 1800FLOWERS is actually owned and mapped to ABC99,
we did not prevent or error out that number. We don't, because it should be
benign as 1800FLOWERS will never attempt to reach RBI99 and therefore the
10 digit logic would never trigger. Further, as an administrative step, if
Ring Central (RBI99) is porting 1800FLOWERS away from ABC99 then for the
previously mentioned translations step they may need to proactively block
1800FLOWERS so that when it does port the TFX does not start routing
traffic to the wrong destination.

The defect, as observed today, appears to be that if Ring Central (RBI99)
enters 1800FLOWERS into their 10 digit block list it becomes *globally*
blocked within the TFX. If this is true, this is most certainly a bug. An
abbreviated order of operations in this matter should be:
1 - Call is received by an originated Resp Org
2 - The Resp Org of the dialed TFN is looked up
3 - A determination is made to see if the receiving resp org is on the TFX
4 - If yes, then the rates are compared
5 - If rates match then routing takes place
6 - Routing consults the 10 digit list for correct routing instructions

It appears that calls are consulting the 10 digit block list globally
before considering the downstream assigned Resp Org Id. This is an error in
the order of operations. If the routing instructions were inherited from
the downstream Resp Org identified the the 10 digit blocks should not be an
issue for the calls going to unidentified Resp Orgs ("URO's.. hah).

Hopefully all this helps!

David Aldworth
President & CEO
O: 303-629-8301
E: daldworth@teliax.com
+1-888-4TELIAX
www.teliax.com
123456789101112

**Comment by CarlsBad505** [comment] 2021-03-05 18:21
Just had a meeting with Christy and Shawn K. I went over all the possible scenarios in the code and I do not believe this is an issue. The code is doing what it's supposed to be doing in each scenario. 

We also do not have any customers complaining about this not working, no concrete evidence, etc.

Back in October, 10 Digit Blocking was still an issue and blocking TFNs globally. We know then, that five9 had thousands of numbers blocked. We also know that if a number is blocked, it will 503 and never have the opportunity to reach a state where we check if "Accept All Traffic" is true. Instead, we exit the call progression well before that.

We also know that we have fixed the 10 Digit Blocking issue about 3 / 4 weeks ago. I believe there was so overlap between that issue and what we perceived to be happening here. I believe the issue we saw here was a side effect of 10 Digit Blocking that was solved already.

Given all this, I am going to close this issue out knowing we will watch this on the back burner.

**Closed** 2021-03-16 03:26 UTC
Labels: kind/backend, kind/enhancement, kind/spike, status/blocked
